import * as fs from 'fs/promises';
import * as path from 'path';
import { BrowserWindow, dialog } from 'electron';

export interface PdfExportResult {
	ok: boolean;
	path?: string;
	error?: string;
}

/**
 * Real PDF generation, not a print dialog - built entirely on Electron's
 * own webContents.printToPDF(), which is already bundled with the app
 * (it's the same Chromium Electron runs on), so this adds no dependency
 * the way a headless-browser library like Puppeteer would. Loads
 * /srs-preview directly (the standalone document page, not the split-view
 * shell) into a hidden window so the PDF is exactly the document, not
 * whatever else happens to be in the other panel.
 */
export async function exportRequirementsPdf(port: number, workspaceName: string): Promise<PdfExportResult> {
	const win = new BrowserWindow({
		show: false,
		webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true }
	});

	try {
		await win.loadURL(`http://localhost:${port}/srs-preview`);
		// displayHeaderFooter:true with no headerTemplate would fall back to
		// Chromium's own default header - the page title (includes the
		// workspace name) plus a date, exactly the kind of "generated by
		// this tool" stamp a client-ready document shouldn't carry. An
		// explicit empty headerTemplate suppresses that; footerTemplate
		// carries only a plain page number, nothing else. The document's
		// own srsDocView.ts print styles (hidden Generate-PDF button, empty
		// meta fields collapsed, forced light colors) handle the rest.
		const pdfBuffer = await win.webContents.printToPDF({
			printBackground: true,
			displayHeaderFooter: true,
			headerTemplate: '<span></span>',
			footerTemplate: '<div style="width:100%;font-family:-apple-system,Helvetica,Arial,sans-serif;font-size:8px;text-align:center;color:#999;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>',
			margins: { top: 0.6, bottom: 0.6, left: 0.5, right: 0.5 }
		});

		const result = await dialog.showSaveDialog({
			title: 'Save Requirements PDF',
			defaultPath: `${workspaceName}-requirements.pdf`,
			filters: [{ name: 'PDF', extensions: ['pdf'] }]
		});
		if (result.canceled || !result.filePath) return { ok: false };

		await fs.writeFile(result.filePath, pdfBuffer);
		return { ok: true, path: path.basename(result.filePath) };
	} catch (error) {
		return { ok: false, error: error instanceof Error ? error.message : String(error) };
	} finally {
		if (!win.isDestroyed()) win.destroy();
	}
}
