import * as fs from 'fs/promises';
import * as path from 'path';
import { BrowserWindow, dialog } from 'electron';
import { PDFDocument } from 'pdf-lib';

export interface PdfExportResult {
	ok: boolean;
	path?: string;
	error?: string;
}

// Chromium's print header/footer templates are static HTML rendered
// outside the page's own document (no access to its stylesheet), so this
// can't just reuse escapeXml from srsDocView.ts - same minimal escaping,
// duplicated because there's no shared module between these two packages
// for something this small.
function escapeHtml(s: string): string {
	return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Chromium's header/footer templates render full paper-width, ignoring the
// left/right values in a printToPDF `margins` option (those only bound the
// body content) - both need their own 0.5in left/right padding, matching
// the body's own side margins, or right-aligned text sits flush against the
// physical page edge instead of lining up with the document's own margin.
const FOOTER_TEMPLATE = '<div style="width:100%;box-sizing:border-box;font-family:-apple-system,Helvetica,Arial,sans-serif;font-size:8px;text-align:right;color:#999;padding:0 0.5in;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>';
const PRINT_MARGINS = { top: 0.75, bottom: 0.65, left: 0.5, right: 0.5 };

function headerTemplate(workspaceName: string): string {
	return `<div style="width:100%;box-sizing:border-box;font-family:-apple-system,Helvetica,Arial,sans-serif;font-size:9px;text-align:right;color:#17203A;text-transform:uppercase;letter-spacing:0.04em;padding:2px 0.5in 0;">${escapeHtml(workspaceName)} &middot; Software Requirements Specification</div>`;
}

// Merges complete PDFs (not just pages) into one document, in order -
// used to stitch the header-less cover page back together with the
// header-carrying rest of the document (see the pageRanges split below).
async function mergePdfs(buffers: Buffer[]): Promise<Buffer> {
	const merged = await PDFDocument.create();
	for (const buf of buffers) {
		const doc = await PDFDocument.load(buf);
		const pages = await merged.copyPages(doc, doc.getPageIndices());
		pages.forEach(page => merged.addPage(page));
	}
	return Buffer.from(await merged.save());
}

/**
 * Real PDF generation, not a print dialog - built entirely on Electron's
 * own webContents.printToPDF(), which is already bundled with the app
 * (it's the same Chromium Electron runs on), so this adds no dependency
 * the way a headless-browser library like Puppeteer would. Loads
 * /srs-preview directly (the standalone document page, not the split-view
 * shell) into a hidden window so the PDF is exactly the document, not
 * whatever else happens to be in the other panel.
 */
export async function exportRequirementsPdf(port: number, workspaceName: string): Promise<PdfExportResult> {
	const win = new BrowserWindow({
		show: false,
		webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true }
	});

	try {
		await win.loadURL(`http://localhost:${port}/srs-preview`);
		// displayHeaderFooter:true with no headerTemplate would fall back to
		// Chromium's own default header - the page title (includes the
		// workspace name) plus a date, exactly the kind of "generated by
		// this tool" stamp a client-ready document shouldn't carry. A real
		// headerTemplate (project name + doc type, right-aligned to match
		// the page-number footer) replaces that - but only from page 2 on,
		// same as a typical printed report's cover page.
		//
		// printToPDF has no "start on page 2" option of its own - the
		// header/footer templates are one static fragment Chromium renders
		// identically on every page (a same-webContents trick of reading
		// the page number in the template's own <script> and hiding the
		// header via CSS was tried first and does NOT work - Chromium
		// already rasterized the header before that script's visibility
		// change takes effect). The reliable way: print the same loaded
		// page twice with different `pageRanges` - once for just page 1
		// with no header, once for "2-" with the real header - then splice
		// the two resulting PDFs together with pdf-lib (naive byte
		// concatenation doesn't produce a valid PDF; the xref/object tables
		// have to be properly merged, which is all pdf-lib is used for
		// here). If the document is only a single page, "2-" is out of
		// range and printToPDF rejects - caught below, falling back to one
		// plain print with the header on every page rather than losing it
		// entirely on a document that never has a page 2 to begin with.
		let pdfBuffer: Buffer;
		try {
			const coverPage = await win.webContents.printToPDF({
				printBackground: true,
				displayHeaderFooter: true,
				headerTemplate: '<span></span>',
				footerTemplate: FOOTER_TEMPLATE,
				margins: PRINT_MARGINS,
				pageRanges: '1'
			});
			const restOfDoc = await win.webContents.printToPDF({
				printBackground: true,
				displayHeaderFooter: true,
				headerTemplate: headerTemplate(workspaceName),
				footerTemplate: FOOTER_TEMPLATE,
				margins: PRINT_MARGINS,
				pageRanges: '2-'
			});
			pdfBuffer = await mergePdfs([coverPage, restOfDoc]);
		} catch {
			pdfBuffer = await win.webContents.printToPDF({
				printBackground: true,
				displayHeaderFooter: true,
				headerTemplate: headerTemplate(workspaceName),
				footerTemplate: FOOTER_TEMPLATE,
				margins: PRINT_MARGINS
			});
		}

		const result = await dialog.showSaveDialog({
			title: 'Save Requirements PDF',
			defaultPath: `${workspaceName}-requirements.pdf`,
			filters: [{ name: 'PDF', extensions: ['pdf'] }]
		});
		if (result.canceled || !result.filePath) return { ok: false };

		await fs.writeFile(result.filePath, pdfBuffer);
		return { ok: true, path: path.basename(result.filePath) };
	} catch (error) {
		return { ok: false, error: error instanceof Error ? error.message : String(error) };
	} finally {
		if (!win.isDestroyed()) win.destroy();
	}
}
